### ISSUE TITLE
More detailed instructions please 

### ISSUE THREAD

**Issue by technopal** [Nedemai/PicoGBCart#1]
Could you put some more detailed instructions on how to compile please? I'm still a newbie at this, I wish you could take the time to do it, thank you very much in advance.

**Comment by Nedemai** [comment]
You can find instructions to setup a IDE to compile in this document. Its very thorough and more comprehensive than I am capable of explaining. https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf
